/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux DESKTOP-645U600 4.4.0-18362-Microsoft x86_64"
#define LGL_COMPILED "Sat Oct 26 18:14:16 WEST 2019"
#define LGL_RELEASED "Thu May 17 11:57:41 CEST 2018"
#define LGL_VERSION "bcj"
#define LGL_ID "78ebb8672540bde0a335aea946bbf32515157d5a"
